### ISSUE TITLE
Transplanting results in [object Object] appearing

### ISSUE THREAD

**Issue by velocity7** [malulleybovo/PSO2AffixingAssistant#29]
**Describe the bug**
See title

**To Reproduce**
Attempt to transplant any item

**Expected behavior**
It's assumed this was supposed to be a numeric up/down that adjusts how many affixes were on the previous item

**Screenshots**
![image](https://user-images.githubusercontent.com/11874183/86520546-a3cd0580-be13-11ea-8670-4c437cce2619.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro 2004
 - Browser: Tested on Firefox, Chrome, IE, Edge

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy S8
 - OS: Android 9
 - Browser: Chrome
 - Version: 83.0.4103.106

**Comment by malulleybovo** [comment]
This issue has been resolved in the latest version.

**Comment by velocity7** [comment]
v1.1.5 got rid of the [object Object] part, but I still don't see the option to reduce the number of affixes (upslotting via affix transplanting is possible at 100% success rate).

**Comment by malulleybovo** [comment]
The option to increase/decrease the number of slots of the material fodder will only appear for cases in which it is possible to do so (such as when the target contains SSAs). Moreover, the option to select an ability to use as an Add Ability Item (or capsule, etc.) will only appear if there is at least one ability for which such item exists.
I see that what you are getting at is what is described in issue https://github.com/malulleybovo/PSO2AffixingAssistant/issues/26.
Therefore, what seems to be happening is that the Assistant's DataBase is outdated. It pulls updates mainly from PSO2 Swiki, but at the moment it does not find any updates involving Add Abilities for Omega Memoria or Reverie Catalyst. This means either the Swiki is outdated or the Assistant's build process is not recognizing this update in Swiki.
Any further discussion about this shall be held in issue https://github.com/malulleybovo/PSO2AffixingAssistant/issues/26.
